INSERT INTO CARGO(CARGO_NAME) VALUES('CHEFE DE DEPARTAMENTO');
INSERT INTO CARGO(CARGO_NAME) VALUES('ARQUITETO');
INSERT INTO CARGO(CARGO_NAME) VALUES('DBA');
INSERT INTO CARGO(CARGO_NAME) VALUES('ANALISTA DE SISTEMAS');
INSERT INTO CARGO(CARGO_NAME) VALUES('ANALISTA DE TESTES');

INSERT INTO DEPARTAMENTO(DEPARTAMENTO_NAME) VALUES('TECNOLOGIA DA INFORMAÇÃO');
INSERT INTO DEPARTAMENTO(DEPARTAMENTO_NAME) VALUES('FINANCEIRO');
INSERT INTO DEPARTAMENTO(DEPARTAMENTO_NAME) VALUES('DEPARTAMENTO PESSOAL');
INSERT INTO DEPARTAMENTO(DEPARTAMENTO_NAME) VALUES('RECURSOS HUMANOS');